[profile.default]
libs = ["lib"]
out = "out"
src = "src"

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"
mumbai = "${MUMBAI_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
etherscan = {key = "${ETHERSCAN_API_KEY}"}

[fmt]
line_length = 100
number_underscore = "thousands"
